# Site settings
title: A blog by Ben Orenstein
email: ben.orenstein@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ben Orenstein's blog.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://benorenstein.com" # the base hostname & protocol for your site
twitter_username: r00k
github_username:  r00k
permalink: "/:title"

# Build settings
markdown: kramdown
